export const API_FETCH_NEWS_APPLE_START = "API_FETCH_NEWS_APPLE_START";
export const API_FETCH_NEWS_APPLE_SUCCESS = "API_FETCH_NEWS_APPLE_SUCCESS";
export const API_FETCH_NEWS_APPLE_FAIL = "API_FETCH_NEWS_APPLE_FAIL";
