export const API_FETCH_NEWS_APPLE_START = "API_FETCH_NEWS_APPLE_START";
export const API_FETCH_NEWS_APPLE_SUCCESS = "API_FETCH_NEWS_APPLE_SUCCESS";
export const API_FETCH_NEWS_APPLE_FAIL = "API_FETCH_NEWS_APPLE_FAIL";

export const API_FETCH_NEWS_TESLA_START = "API_FETCH_NEWS_TESLA_START";
export const API_FETCH_NEWS_TESLA_SUCCESS = "API_FETCH_NEWS_TESLA_SUCCESS";
export const API_FETCH_NEWS_TESLA_FAIL = "API_FETCH_NEWS_TESLA_FAIL";

export const API_FETCH_NEWS_KEYWORD_START = "API_FETCH_NEWS_KEYWORD_START";
export const API_FETCH_NEWS_KEYWORD_SUCCESS = "API_FETCH_NEWS_KEYWORD_SUCCESS";
export const API_FETCH_NEWS_KEYWORD_FAIL = "API_FETCH_NEWS_KEYWORD_FAIL";
