export const API_FETCH_NEWS_APPLE_START = "API_FETCH_NEWS_APPLE_START";
export const API_FETCH_NEWS_APPLE_SUCCESS = "API_FETCH_NEWS_APPLE_SUCCESS";
export const API_FETCH_NEWS_APPLE_FAIL = "API_FETCH_NEWS_APPLE_FAIL";

export const API_FETCH_NEWS_TESLA_START = "API_FETCH_NEWS_TESLA_START";
export const API_FETCH_NEWS_TESLA_SUCCESS = "API_FETCH_NEWS_TESLA_SUCCESS";
export const API_FETCH_NEWS_TESLA_FAIL = "API_FETCH_NEWS_TESLA_FAIL";

export const API_FETCH_NEWS_KEYWORD_START = "API_FETCH_NEWS_KEYWORD_START";
export const API_FETCH_NEWS_KEYWORD_SUCCESS = "API_FETCH_NEWS_KEYWORD_SUCCESS";
export const API_FETCH_NEWS_KEYWORD_FAIL = "API_FETCH_NEWS_KEYWORD_FAIL";

export const API_FETCH_GITHUB_REPOS_START = "API_FETCH_GITHUB_REPOS_START";
export const API_FETCH_GITHUB_REPOS_SUCCESS = "API_FETCH_GITHUB_REPOS_SUCCESS";
export const API_FETCH_GITHUB_REPOS_FAIL = "API_FETCH_GITHUB_REPOS_FAIL";

export const API_FETCH_DEV_TO_ARTICLES_START =
  "API_FETCH_DEV_TO_ARTICLES_START";
export const API_FETCH_DEV_TO_ARTICLES_SUCCESS =
  "API_FETCH_DEV_TO_ARTICLES_SUCCESS";
export const API_FETCH_DEV_TO_ARTICLES_FAIL = "API_FETCH_DEV_TO_ARTICLES_FAIL";

export const API_FETCH_CONTEST_START = "API_FETCH_CONTEST_START";
export const API_FETCH_CONTEST_SUCCESS = "API_FETCH_CONTEST_SUCCESS";
export const API_FETCH_CONTEST_FAIL = "API_FETCH_CONTEST_FAIL";
