export const GOOGLE_SIGN_IN_START = "GOOGLE_SIGN_IN_START";
export const GOOGLE_SIGN_IN_SUCCESS = "GOOGLE_SIGN_IN_SUCCESS";
export const GOOGLE_SIGN_IN_FAIL = "GOOGLE_SIGN_IN_FAIL";

export const TWITTER_SIGN_IN_START = "TWITTER_SIGN_IN_START";
export const TWITTER_SIGN_IN_SUCCESS = "TWITTER_SIGN_IN_SUCCESS";
export const TWITTER_SIGN_IN_FAIL = "TWITTER_SIGN_IN_FAIL";

export const LOAD_USER_START = "LOAD_USER_START";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";
